version: "3.8"

services:
  mc_modded_lite:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    stop_grace_period: 240s
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: FORGE
      VERSION: 1.20.1
      FORGE_VERSION: 47.1.0
      MODPACK: https://nc.conceptual.ca/index.php/s/B8yTXinQLBMW6ae/download/CPModdedLite.zip
      REMOVE_OLD_MODS: true

      SERVER_NAME: CP Lite
      MOTD: CP Lightly Modded Server
      MODE: survival
      SEED: "-2082072440"
      ALLOW_FLIGHT: true
      SPAWN_PROTECTION: 0
      
      TZ: America/Toronto
      INIT_MEMORY: 3G
      MAX_MEMORY: 6G
      ENABLE_ROLLING_LOGS: true
      SNOOPER_ENABLED: false
      STOP_SERVER_ANNOUNCE_DELAY: 60

    volumes:
      - ./data:/data
