version: "3.8"

services:
  mc_modded_lite:
    image: itzg/minecraft-server
    container_name: mc_modded_lite
    tty: true
    stdin_open: true
    stop_grace_period: 240s
    ports:
      - "25565:25565"
    environment:
      CF_API_KEY: ${CF_API_KEY}
      TYPE: AUTO_CURSEFORGE
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/cpmoddedlite/files/4671016
      CF_PARALLEL_DOWNLOADS: 8
      
      CF_EXCLUDE_MODS: chat-heads,libipn,betterf3,fusion-connected-textures
 
      EULA: "TRUE"
      SERVER_NAME: CP Lite
      MOTD: CP Learn To Tech
      MODE: survival
      SEED: "-2082072440"
      ALLOW_FLIGHT: true
      SPAWN_PROTECTION: 0
      
      TZ: America/Toronto
      INIT_MEMORY: 3G
      MAX_MEMORY: 6G
      ENABLE_ROLLING_LOGS: true
      SNOOPER_ENABLED: false
      STOP_SERVER_ANNOUNCE_DELAY: 60

    volumes:
      - ./data:/data
      - ./downloads:/downloads
